/* Table Deparments */
DROP TABLE IF EXISTS departments;
CREATE TABLE IF NOT EXISTS departments( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;

INSERT INTO departments(`id`, `name`) VALUES (1, "Santander");
INSERT INTO departments(`id`, `name`) VALUES (2, "Caqueta");
INSERT INTO departments(`id`, `name`) VALUES (3, "San Andres");
INSERT INTO departments(`id`, `name`) VALUES (4, "Bolivar");
INSERT INTO departments(`id`, `name`) VALUES (5, "Quindio");
INSERT INTO departments(`id`, `name`) VALUES (6, "Guaviare");
INSERT INTO departments(`id`, `name`) VALUES (7, "Cundinamarca");
INSERT INTO departments(`id`, `name`) VALUES (8, "Cordoba");
INSERT INTO departments(`id`, `name`) VALUES (9, "Cauca");
INSERT INTO departments(`id`, `name`) VALUES (10, "Vichada");
INSERT INTO departments(`id`, `name`) VALUES (11, "Tolima");
INSERT INTO departments(`id`, `name`) VALUES (12, "La Guajira");
INSERT INTO departments(`id`, `name`) VALUES (13, "Norte de Santander");
INSERT INTO departments(`id`, `name`) VALUES (14, "Arauca");
INSERT INTO departments(`id`, `name`) VALUES (15, "Valle");
INSERT INTO departments(`id`, `name`) VALUES (16, "Amazonas");
INSERT INTO departments(`id`, `name`) VALUES (17, "Caldas");
INSERT INTO departments(`id`, `name`) VALUES (18, "Atlantico");
INSERT INTO departments(`id`, `name`) VALUES (19, "Sucre");
INSERT INTO departments(`id`, `name`) VALUES (20, "Huila");
INSERT INTO departments(`id`, `name`) VALUES (21, "Santafe de Bogota");
INSERT INTO departments(`id`, `name`) VALUES (22, "Putumayo");
INSERT INTO departments(`id`, `name`) VALUES (23, "Vaupes");
INSERT INTO departments(`id`, `name`) VALUES (24, "Magdalena");
INSERT INTO departments(`id`, `name`) VALUES (25, "Risaralda");
INSERT INTO departments(`id`, `name`) VALUES (26, "Boyaca");
INSERT INTO departments(`id`, `name`) VALUES (27, "Antioquia");
INSERT INTO departments(`id`, `name`) VALUES (28, "Meta");
INSERT INTO departments(`id`, `name`) VALUES (29, "Guainia");
INSERT INTO departments(`id`, `name`) VALUES (30, "Narino");
INSERT INTO departments(`id`, `name`) VALUES (31, "Casanare");
INSERT INTO departments(`id`, `name`) VALUES (32, "Cesar");
INSERT INTO departments(`id`, `name`) VALUES (33, "Choco");

/* Table Cities */
DROP TABLE IF EXISTS cities;
CREATE TABLE IF NOT EXISTS cities( `id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(255) NOT NULL, `department_id` int(11) NOT NULL, PRIMARY KEY (`id`), FOREIGN KEY (`department_id`) REFERENCES departments(`id`)) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;;

INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1, "Aguada", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (2, "Albania", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (3, "Aratoca", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (4, "Barbosa", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (5, "Barichara", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (6, "Barrancabermeja", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (7, "Betulia", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (8, "Bolivar", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (9, "Bucaramanga", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (10, "Cabrera", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (11, "California", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (12, "Capitanejo", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (13, "Carcasi", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (14, "Cepita", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (15, "Cerrito", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (16, "Charala", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (17, "Charta", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (18, "Chima", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (19, "Chipata", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (20, "Cimitarra", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (21, "Concepcion", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (22, "Confines", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (23, "Contratacion", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (24, "Coromoro", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (25, "Curiti", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (26, "El Carmen", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (27, "El Guacamayo", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (28, "El Penon", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (29, "El Playon", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (30, "Encino", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (31, "Enciso", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (32, "Florian", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (33, "Floridablanca", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (34, "Galan", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (35, "Gambita", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (36, "Giron", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (37, "Guaca", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (38, "Guadalupe", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (39, "Guapota", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (40, "Guavata", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (41, "Guepsa", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (42, "Hato", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (43, "Jesus Maria", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (44, "Jordan", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (45, "La Belleza", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (46, "Landazuri", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (47, "La Paz", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (48, "Lebrija", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (49, "Los Santos", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (50, "Macaravita", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (51, "Malaga", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (52, "Matanza", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (53, "Mogotes", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (54, "Molagavita", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (55, "Ocamonte", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (56, "Oiba", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (57, "Onzaga", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (58, "Palmar", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (59, "Palmas del Socorro", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (60, "Paramo", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (61, "Pie de Cuesta", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (62, "Pinchote", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (63, "Puente Nacional", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (64, "Puerto Parra", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (65, "Puerto Wilches", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (66, "Rionegro", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (67, "Sabana de Torres", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (68, "San Andres", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (69, "San Benito", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (70, "San Gil", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (71, "San Joaquin", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (72, "San Jose de Miranda", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (73, "San Miguel", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (74, "San Vicente de Chucuri", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (75, "Santa Barbara", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (76, "Santa Helena del Opon", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (77, "Simacota", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (78, "Socorro", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (79, "Suaita", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (80, "Sucre", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (81, "Surata", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (82, "Tona", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (83, "Valle de San Jose", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (84, "Velez", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (85, "Vetas", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (86, "Villanueva", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (87, "Zapatoca", 1 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (88, "Albania", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (89, "Belen de los Andaquies", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (90, "Cartagena del Chaira", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (91, "Curillo", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (92, "El Doncello", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (93, "El Paujil", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (94, "Florencia", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (95, "La Montanita", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (96, "Milan", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (97, "Morelia", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (98, "Puerto Rico", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (99, "San Jose del Fragua", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (100, "San Vicente del Caguan", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (101, "Solano", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (102, "Solita", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (103, "Valparaiso", 2 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (104, "Providencia", 3 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (105, "San Andres", 3 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (106, "Cartagena", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (107, "Achi", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (108, "Altos del Rosario", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (109, "Arenal", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (110, "Arjona", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (111, "Arroyohondo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (112, "Barranco de Loba", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (113, "Calamar", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (114, "Cantagallo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (115, "Cicuto", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (116, "Cordoba", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (117, "Clemencia", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (118, "El Carmen de Bolivar", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (119, "El Guamo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (120, "El Penon", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (121, "Hatillo de Loba", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (122, "Magangue", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (123, "Mahates", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (124, "Margarita", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (125, "Maria la Baja", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (126, "Montecristo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (127, "Mompos", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (128, "Morales", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (129, "Pinillos", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (130, "Regidor", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (131, "Rio Viejo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (132, "San Cristobal", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (133, "San Estanislao", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (134, "San Fernando", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (135, "San Jacinto", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (136, "San Jacinto del Cauca", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (137, "San Juan Nepomuceno", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (138, "San Martin de Loba", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (139, "San Pablo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (140, "Santa Catalina", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (141, "Santa Rosa", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (142, "Santa Rosa del Sur", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (143, "Simiti", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (144, "Soplaviento", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (145, "Talaigua Nuevo", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (146, "Tiquisio (Puerto Rico)", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (147, "Turbaco", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (148, "Turbana", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (149, "Villanueva", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (150, "Zambrano", 4 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (151, "Armenia", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (152, "Buenavista", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (153, "Calarca", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (154, "Circasia", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (155, "Cordoba", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (156, "Filandia", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (157, "Genova", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (158, "La Tebaida", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (159, "Montenegro", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (160, "Pijao", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (161, "Quimbaya", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (162, "Salento", 5 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (163, "Calamar", 6 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (164, "El Retorno", 6 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (165, "Miraflores", 6 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (166, "San Jose del Guaviare", 6 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (167, "Agua de Dios", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (168, "Alban", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (169, "Anapoima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (170, "Anolaima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (171, "Arbelaez", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (172, "Beltran", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (173, "Bituima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (174, "Bojaca", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (175, "Cabrera", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (176, "Cachipay", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (177, "Cajica", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (178, "Caparrapi", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (179, "Caqueza", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (180, "Carmen de Carupa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (181, "Chaguani", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (182, "Chia", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (183, "Chipaque", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (184, "Choachi", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (185, "Choconta", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (186, "Cogua", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (187, "Cota", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (188, "Cucunuba", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (189, "El Colegio", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (190, "El Penon", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (191, "El Rosal", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (192, "Facatativa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (193, "Fomeque", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (194, "Fosca", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (195, "Funza", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (196, "Fuquene", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (197, "Fusagasuga", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (198, "Gachala", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (199, "Gachancipa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (200, "Gacheta", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (201, "Gama", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (202, "Girardot", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (203, "Granada", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (204, "Guacheta", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (205, "Guaduas", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (206, "Guasca", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (207, "Guataqui", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (208, "Guatavita", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (209, "Guayabal de Siquima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (210, "Guayabetal", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (211, "Gutierrez", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (212, "Jerusalen", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (213, "Junin", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (214, "La Calera", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (215, "La Mesa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (216, "La Palma", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (217, "La Pena", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (218, "La Vega", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (219, "Lenguazaque", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (220, "Macheta", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (221, "Madrid", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (222, "Manta", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (223, "Medina", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (224, "Mosquera", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (225, "Narino", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (226, "Nemocon", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (227, "Nilo", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (228, "Nimaima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (229, "Nocaima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (230, "Venecia (Ospina Perez)", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (231, "Pacho", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (232, "Paime", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (233, "Pandi", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (234, "Paratebueno", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (235, "Pasca", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (236, "Puerto Salgar", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (237, "Puli", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (238, "Quebradanegra", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (239, "Quetame", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (240, "Quipile", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (241, "Rafael", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (242, "Ricaurte", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (243, "San Antonio de Tequendama", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (244, "San Bernardo", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (245, "San Cayetano", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (246, "San Francisco", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (247, "San Juan de Rioseco", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (248, "Sasaima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (249, "Sesquile", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (250, "Sibate", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (251, "Silvania", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (252, "Simijaca", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (253, "Soacha", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (254, "Sopo", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (255, "Subachoque", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (256, "Suesca", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (257, "Supata", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (258, "Susa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (259, "Sutatausa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (260, "Tabio", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (261, "Tausa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (262, "Tena", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (263, "Tenjo", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (264, "Tibacuy", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (265, "Tibirita", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (266, "Tocaima", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (267, "Tocancipa", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (268, "Topaipi", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (269, "Ubala", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (270, "Ubaque", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (271, "Ubate", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (272, "Une", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (273, "utica", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (274, "Vergara", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (275, "Viani", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (276, "Villagomez", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (277, "Villapinzon", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (278, "Villeta", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (279, "Viota", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (280, "Yacopi", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (281, "Zipacon", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (282, "Zipaquira", 7 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (283, "Ayapel", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (284, "Buenavista", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (285, "Canalete", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (286, "Cerete", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (287, "Chima", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (288, "Chinu", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (289, "Cienaga de Oro", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (290, "Cotorra", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (291, "La Apartada (Frontera)", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (292, "Lorica", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (293, "Los Cordobas", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (294, "Momil", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (295, "Monitos", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (296, "Montelibano", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (297, "Monteria", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (298, "Planeta Rica", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (299, "Pueblo Nuevo", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (300, "Puerto Escondido", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (301, "Puerto Libertador", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (302, "Purisima", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (303, "Sahagun", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (304, "San Andres Sotavento", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (305, "San Antero", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (306, "San Bernardo del Viento", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (307, "San Carlos", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (308, "San Pelayo", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (309, "Tierralta", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (310, "Valencia", 8 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (311, "Almaguer", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (312, "Argelia", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (313, "Balboa", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (314, "Bolivar", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (315, "Buenos Aires", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (316, "Cajibio", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (317, "Caldono", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (318, "Caloto", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (319, "Corinto", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (320, "El Tambo", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (321, "Florencia", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (322, "Guapi", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (323, "Inza", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (324, "Jambalo", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (325, "La Sierra", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (326, "La Vega", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (327, "Lopez (Micay)", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (328, "Mercaderes", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (329, "Miranda", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (330, "Morales", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (331, "Padilla", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (332, "Paez (Belalcazar)", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (333, "Patia (El Bordo)", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (334, "Piamonte", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (335, "Piendamo", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (336, "Popayan", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (337, "Puerto Tejada", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (338, "Purace (Coconuco)", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (339, "Rosas", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (340, "San Sebastian", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (341, "Santander de Quilichao", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (342, "Santa Rosa", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (343, "Silvia", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (344, "Sotara (Paispamba)", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (345, "Suarez", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (346, "Timbio", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (347, "Timbiqui", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (348, "Toribio", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (349, "Totoro", 9 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (350, "La Primavera", 10 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (351, "Puerto Carreno", 10 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (352, "Santa Rosalia", 10 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (353, "Cumaribo", 10 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (354, "Alpujarra", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (355, "Alvarado", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (356, "Ambalema", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (357, "Anzoategui", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (358, "Armero (Guayabal)", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (359, "Ataco", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (360, "Cajamarca", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (361, "Carmen de Apicala", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (362, "Casabianca", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (363, "Chaparral", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (364, "Coello", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (365, "Coyaima", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (366, "Cunday", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (367, "Dolores", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (368, "Espinal", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (369, "Falan", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (370, "Flandes", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (371, "Fresno", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (372, "Guamo", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (373, "Herveo", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (374, "Honda", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (375, "Ibague", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (376, "Icononzo", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (377, "Lerida", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (378, "Libano", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (379, "Mariquita", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (380, "Melgar", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (381, "Murillo", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (382, "Natagaima", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (383, "Ortega", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (384, "Palocabildo", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (385, "Piedras", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (386, "Planadas", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (387, "Prado", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (388, "Purificacion", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (389, "Rioblanco", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (390, "Roncesvalles", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (391, "Rovira", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (392, "Saldana", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (393, "San Antonio", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (394, "San Luis", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (395, "Santa Isabel", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (396, "Suarez", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (397, "Valle de San Juan", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (398, "Venadillo", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (399, "Villahermosa", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (400, "Villarrica", 11 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (401, "Barrancas", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (402, "Dibulla", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (403, "Distraccion", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (404, "El Molino", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (405, "Fonseca", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (406, "Hatonuevo", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (407, "Maicao", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (408, "Manaure", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (409, "Riohacha", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (410, "San Juan del Cesar", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (411, "Uribia", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (412, "Urumita", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (413, "Villanueva", 12 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (414, "Abrego", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (415, "Arboledas", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (416, "Bochalema", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (417, "Bucarasica", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (418, "Cacota", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (419, "Cachira", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (420, "Chinacota", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (421, "Chitaga", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (422, "Convencion", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (423, "Cucuta", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (424, "Cucutilla", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (425, "Durania", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (426, "El Carmen", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (427, "El Tarra", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (428, "El Zulia", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (429, "Gramalote", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (430, "Hacari", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (431, "Herran", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (432, "Labateca", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (433, "La Esperanza", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (434, "La Playa", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (435, "Los Patios", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (436, "Lourdes", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (437, "Mutiscua", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (438, "Ocana", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (439, "Pamplona", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (440, "Pamplonita", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (441, "Puerto Santander", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (442, "Ragonvalia", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (443, "Salazar", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (444, "San Calixto", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (445, "San Cayetano", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (446, "Santiago", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (447, "Sardinata", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (448, "Silos", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (449, "Teorama", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (450, "Tibu", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (451, "Toledo", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (452, "Villacaro", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (453, "Villa del Rosario", 13 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (454, "Arauca", 14 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (455, "Arauquita", 14 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (456, "Cravo Norte", 14 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (457, "Fortul", 14 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (458, "Saravena", 14 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (459, "Tame", 14 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (460, "Alcala", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (461, "Andalucia", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (462, "Ansermanuevo", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (463, "Argelia", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (464, "Bolivar", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (465, "Buenaventura", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (466, "Buga", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (467, "Bugalagrande", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (468, "Caicedonia", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (469, "Cali", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (470, "Calima (Darien)", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (471, "Candelaria", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (472, "Cartago", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (473, "Dagua", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (474, "El aguila", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (475, "El Cairo", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (476, "El Cerrito", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (477, "El Dovio", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (478, "Florida", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (479, "Ginebra", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (480, "Guacari", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (481, "Jamundi", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (482, "La Cumbre", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (483, "La Union", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (484, "La Victoria", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (485, "Obando", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (486, "Palmira", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (487, "Pradera", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (488, "Restrepo", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (489, "Riofrio", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (490, "Roldanillo", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (491, "San Pedro", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (492, "Sevilla", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (493, "Toro", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (494, "Trujillo", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (495, "Tulua", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (496, "Ulloa", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (497, "Versalles", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (498, "Vijes", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (499, "Yotoco", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (500, "Yumbo", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (501, "Zarzal", 15 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (502, "Leticia", 16 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (503, "Puerto Narino", 16 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (504, "Aguadas", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (505, "Anserma", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (506, "Aranzazu", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (507, "Belalcazar", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (508, "Chinchina", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (509, "Filadelfia", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (510, "La Dorada", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (511, "La Merced", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (512, "Manizales", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (513, "Manzanares", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (514, "Marmato", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (515, "Marquetalia", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (516, "Marulanda", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (517, "Neira", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (518, "Pacora", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (519, "Palestina", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (520, "Pensilvania", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (521, "Riosucio", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (522, "Risaralda", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (523, "Salamina", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (524, "Samana", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (525, "San Jose", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (526, "Supia", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (527, "Victoria", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (528, "Villamaria", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (529, "Viterbo", 17 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (530, "Barranquilla", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (531, "Baranoa", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (532, "Campo de la Cruz", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (533, "Candelaria", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (534, "Galapa", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (535, "Juan de Acosta", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (536, "Luruaco", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (537, "Malambo", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (538, "Manati", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (539, "Palmar de Varela", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (540, "Piojo", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (541, "Polonuevo", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (542, "Ponedera", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (543, "Puerto Colombia", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (544, "Repelon", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (545, "Sabanagrande", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (546, "Sabanalarga", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (547, "Santa Lucia", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (548, "Santo Tomas", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (549, "Soledad", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (550, "Suan", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (551, "Tubara", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (552, "Usiacuri", 18 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (553, "Buenavista", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (554, "Caimito", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (555, "Coloso (Ricaurte)", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (556, "Corozal", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (557, "Chalan", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (558, "Galeras (Nueva Granada)", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (559, "Guaranda", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (560, "La Union", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (561, "Los Palmitos", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (562, "Majagual", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (563, "Morroa", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (564, "Ovejas", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (565, "Palmito", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (566, "Sampues", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (567, "San Benito Abad", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (568, "San Juan de Betulia", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (569, "San Marcos", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (570, "San Onofre", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (571, "San Pedro", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (572, "Since", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (573, "Sincelejo", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (574, "Sucre", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (575, "Tolu", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (576, "Toluviejo", 19 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (577, "Acevedo", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (578, "Agrado", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (579, "Aipe", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (580, "Algeciras", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (581, "Altamira", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (582, "Baraya", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (583, "Campoalegre", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (584, "Colombia", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (585, "Elias", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (586, "Garzon", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (587, "Gigante", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (588, "Guadalupe", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (589, "Hobo", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (590, "Iquira", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (591, "Isnos", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (592, "La Argentina", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (593, "La Plata", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (594, "Nataga", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (595, "Neiva", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (596, "Oporapa", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (597, "Paicol", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (598, "Palermo", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (599, "Palestina", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (600, "Pital", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (601, "Pitalito", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (602, "Rivera", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (603, "Saladoblanco", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (604, "San Agustin", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (605, "Santa Maria", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (606, "Suaza", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (607, "Tarqui", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (608, "Tesalia", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (609, "Tello", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (610, "Teruel", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (611, "Timana", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (612, "Villavieja", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (613, "Yaguara", 20 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (614, "Santafe de Bogota", 21 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (615, "Colon", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (616, "Mocoa", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (617, "Orito", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (618, "Puerto Asis", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (619, "Puerto Caicedo", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (620, "Puerto Guzman", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (621, "Puerto Leguizamo", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (622, "Sibundoy", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (623, "San Francisco", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (624, "San Miguel", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (625, "Santiago", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (626, "Villa Gamuez (La Hormiga)", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (627, "Villa Garzon", 22 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (628, "Caruru", 23 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (629, "Mitu", 23 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (630, "Tatama", 23 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (631, "Aracataca", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (632, "Ariguani (El Dificil)", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (633, "Cerro San Antonio", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (634, "Chivolo", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (635, "Cienaga", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (636, "El Banco", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (637, "El Pinon", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (638, "El Reten", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (639, "Fundacion", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (640, "Guamal", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (641, "Pedraza", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (642, "Pijino del Carmen", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (643, "Pivijay", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (644, "Plato", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (645, "Publoviejo", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (646, "Remolino", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (647, "Salamina", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (648, "San Sebastian de Buuenavista", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (649, "San Zenon", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (650, "Santa Ana", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (651, "Santa Marta", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (652, "Sitionuevo", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (653, "Tenerife", 24 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (654, "Apia", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (655, "Balboa", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (656, "Belen de Umbria", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (657, "Dos Quebradas", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (658, "Guatica", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (659, "La Celia", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (660, "La Virginia", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (661, "Marsella", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (662, "Mistrato", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (663, "Pereira", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (664, "Pueblo Rico", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (665, "Quinchia", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (666, "Santa Rosa de Cabal", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (667, "Santuario", 25 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (668, "Almeida", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (669, "Aquitania", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (670, "Arcabuco", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (671, "Belen", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (672, "Berbeo", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (673, "Beteitiva", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (674, "Boavita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (675, "Boyaca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (676, "Briseno", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (677, "Buenavista", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (678, "Busbanza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (679, "Caldas", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (680, "Campohermoso", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (681, "Cerinza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (682, "Chinavita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (683, "Chiquinquira", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (684, "Chiscas", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (685, "Chita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (686, "Chitaranque", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (687, "Chivata", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (688, "Cienaga", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (689, "Combita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (690, "Coper", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (691, "Corrales", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (692, "Covarachia", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (693, "Cubar", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (694, "Cucaita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (695, "Cuitiva", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (696, "Chiquiza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (697, "Chivor", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (698, "Duitama", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (699, "El Cocuy", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (700, "El Espino", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (701, "Firavitoba", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (702, "Floresta", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (703, "Gachantiva", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (704, "Gameza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (705, "Garagoa", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (706, "Guacamayas", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (707, "Guateque", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (708, "Guayata", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (709, "Guican", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (710, "Iza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (711, "Jenesano", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (712, "Jerico", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (713, "Labranzagrande", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (714, "La Capilla", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (715, "La Victoria", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (716, "La Ubita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (717, "Villa de Leyva", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (718, "Macanal", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (719, "Maripi", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (720, "Miraflores", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (721, "Mongua", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (722, "Mongui", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (723, "Moniquira", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (724, "Motavita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (725, "Muzo", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (726, "Nobsa", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (727, "Nuevo Colon", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (728, "Oicata", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (729, "Otanche", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (730, "Pachavita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (731, "Paez", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (732, "Paipa", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (733, "Pajarito", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (734, "Panqueba", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (735, "Pauna", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (736, "Paya", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (737, "Paz de Rio", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (738, "Pesca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (739, "Pisva", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (740, "Puerto Boyaca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (741, "Quipama", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (742, "Ramiquiri", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (743, "Raquira", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (744, "Rondon", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (745, "Saboya", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (746, "Sachica", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (747, "Samaca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (748, "San Eduardo", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (749, "San Jose de Pare", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (750, "San Luis de Gaceno", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (751, "San Mateo", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (752, "San Miguel de Sema", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (753, "San Pablo de Borbur", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (754, "Santana", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (755, "Santa Maria", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (756, "Santa Rosa de Viterbo", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (757, "Santa Sofia", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (758, "Sativanorte", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (759, "Sativasur", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (760, "Siachoque", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (761, "Soata", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (762, "Socota", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (763, "Socha", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (764, "Sogamoso", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (765, "Somondoco", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (766, "Sora", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (767, "Sotaquira", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (768, "Soraca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (769, "Susacon", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (770, "Sutamarchan", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (771, "Sutatenza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (772, "Tasco", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (773, "Tenza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (774, "Tibana", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (775, "Tibasosa", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (776, "Tinjaca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (777, "Tipacoque", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (778, "Toca", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (779, "Togui", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (780, "Topaga", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (781, "Tota", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (782, "Tunja", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (783, "Tunungua", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (784, "Turmeque", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (785, "Tuta", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (786, "Tutaza", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (787, "Umbita", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (788, "Ventaquemada", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (789, "Viracacha", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (790, "Zetaquira", 26 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (791, "Abejorral", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (792, "Abriaqui", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (793, "Alejandria", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (794, "Amaga", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (795, "Amalfi", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (796, "Andes", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (797, "Angelopolis", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (798, "Angostura", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (799, "Anori", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (800, "Antioquia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (801, "Anza", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (802, "Apartado", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (803, "Arboletes", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (804, "Argelia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (805, "Armenia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (806, "Barbosa", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (807, "Belmira", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (808, "Bello", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (809, "Betania", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (810, "Betulia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (811, "Bolivar", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (812, "Briseno", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (813, "Buritica", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (814, "Caceres", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (815, "Caicedo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (816, "Caldas", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (817, "Campamento", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (818, "Canasgordas", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (819, "Caracoli", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (820, "Caramanta", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (821, "Carepa", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (822, "Carmen de Viboral", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (823, "Carolina", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (824, "Caucasia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (825, "Chigorodo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (826, "Cisneros", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (827, "Cocorna", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (828, "Concepcion", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (829, "Concordia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (830, "Copacabana", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (831, "Dabeiba", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (832, "Don Matias", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (833, "Ebejico", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (834, "El Bagre", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (835, "Entrerrios", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (836, "Envigado", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (837, "Fredonia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (838, "Frontino", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (839, "Giraldo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (840, "Girardota", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (841, "Gomez Plata", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (842, "Granada", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (843, "Guadalupe", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (844, "Guarne", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (845, "Guatape", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (846, "Heliconia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (847, "Hispania", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (848, "Itagui", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (849, "Ituango", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (850, "Jardin", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (851, "Jerico", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (852, "La Ceja", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (853, "La Estrella", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (854, "La Pintada", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (855, "La Union", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (856, "Liborina", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (857, "Maceo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (858, "Marinilla", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (859, "Medellin", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (860, "Montebello", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (861, "Murindo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (862, "Mutata", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (863, "Narino", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (864, "Necocli", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (865, "Nechi", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (866, "Olaya", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (867, "Penol", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (868, "Peque", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (869, "Pueblorrico", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (870, "Puerto Berrio", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (871, "Puerto Nare", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (872, "Puerto Triunfo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (873, "Remedios", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (874, "Retiro", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (875, "Rionegro", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (876, "Sabanalarga", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (877, "Sabaneta", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (878, "Salgar", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (879, "San Andres", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (880, "San Carlos", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (881, "San francisco", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (882, "San Jeronimo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (883, "San Jose de Montana", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (884, "San Juan de Uraba", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (885, "San Luis", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (886, "San Pedro", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (887, "San Pedro de Uraba", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (888, "San Rafael", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (889, "San Roque", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (890, "San Vicente", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (891, "Santa Barbara", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (892, "Santa Rosa de Osos", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (893, "Santo Domingo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (894, "Santuario", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (895, "Segovia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (896, "Sonson", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (897, "Sopetran", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (898, "Tamesis", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (899, "Taraza", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (900, "Tarso", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (901, "Titiribi", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (902, "Toledo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (903, "Turbo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (904, "Uramita", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (905, "Urrao", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (906, "Valdivia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (907, "Valparaiso", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (908, "Vegachi", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (909, "Venecia", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (910, "Vigia del Fuerte", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (911, "Yali", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (912, "Yarumal", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (913, "Yolombo", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (914, "Yondo (Casabe)", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (915, "Zaragoza", 27 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (916, "Acacias", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (917, "Barranca de Upia", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (918, "Cabuyaro", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (919, "Castilla la Nueva", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (920, "Cubarral", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (921, "Cumaral", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (922, "El Calvario", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (923, "El Castillo", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (924, "El Dorado", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (925, "Fuente de Oro", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (926, "Granada", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (927, "Guamal", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (928, "Mapiripan", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (929, "Mesetas", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (930, "La Macarena", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (931, "La Uribe", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (932, "Lejanias", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (933, "Puerto Concordia", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (934, "Puerto Gaitan", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (935, "Puerto Lopez", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (936, "Puerto Lleras", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (937, "Puerto Rico", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (938, "Restrepo", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (939, "San Carlos de Guaroa", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (940, "San Juan de Arama", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (941, "San Juanito", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (942, "San Martin", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (943, "Villavicencio", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (944, "Vistahermosa", 28 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (945, "Puerto Inirida", 29 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (946, "Alban (San Jose)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (947, "Aldana", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (948, "Ancuya", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (949, "Arboleda (Berruecos)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (950, "Barbacoas", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (951, "Belen", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (952, "Buesaco", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (953, "Colon (Genova)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (954, "Consaca", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (955, "Contadero", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (956, "Cordoba", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (957, "Cuaspud (Carlosama)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (958, "Cumbal", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (959, "Cumbitara", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (960, "Chachagui", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (961, "El Charco", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (962, "El Rosario", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (963, "El Tablon", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (964, "El Tambo", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (965, "Francisco Pizarro", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (966, "Funes", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (967, "Guachucal", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (968, "Guaitarilla", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (969, "Gualmatan", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (970, "Iles", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (971, "Imues", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (972, "Ipiales", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (973, "La Cruz", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (974, "La Florida", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (975, "La Llanada", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (976, "La Tola", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (977, "La Union", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (978, "Leiva", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (979, "Linares", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (980, "Los Andes (Sotomayor)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (981, "Magui (Payan)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (982, "Mallama (Piedrancha)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (983, "Mosquera", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (984, "Olaya", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (985, "Ospina", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (986, "Pasto", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (987, "Policarpa", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (988, "Potosi", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (989, "Providencia", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (990, "Puerres", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (991, "Pupiales", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (992, "Ricaurte", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (993, "Roberto Payan (San Jose)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (994, "Samaniego", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (995, "Sandona", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (996, "San Bernardo", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (997, "San Lorenzo", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (998, "San Pablo", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (999, "San Pedro de Cartago", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1000, "Santa Barbara (Iscuande)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1001, "Santa Cruz (Guachavez)", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1002, "Sapuyes", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1003, "Taminango", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1004, "Tangua", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1005, "Tumaco", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1006, "Tuquerres", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1007, "Yacuanquer", 30 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1008, "Aguazul", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1009, "Chameza", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1010, "Hato Corozal", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1011, "La Salina", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1012, "Mani", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1013, "Monterrey", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1014, "Nunchia", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1015, "Orocue", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1016, "Paz de Ariporo", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1017, "Pore", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1018, "Recetor", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1019, "Sabalarga", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1020, "Sacama", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1021, "San Luis de Palenque", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1022, "Tamara", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1023, "Tauramena", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1024, "Trinidad", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1025, "Villanueva", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1026, "Yopal", 31 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1027, "Aguachica", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1028, "Agustin Codazzi", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1029, "Astrea", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1030, "Becerril", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1031, "Bosconia", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1032, "Chimichagua", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1033, "Chiriguana", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1034, "Curumani", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1035, "El Copey", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1036, "El Paso", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1037, "Gamarra", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1038, "Gonzalez", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1039, "La Gloria", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1040, "La Jagua de Ibirico", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1041, "Manaure Balcon Cesar", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1042, "Pailitas", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1043, "Pelaya", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1044, "Pueblo Bello", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1045, "Rio de Oro", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1046, "La Paz (Robles)", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1047, "San Alberto", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1048, "San Diego", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1049, "San Martin", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1050, "Tamalameque", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1051, "Valledupar", 32 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1052, "Acandi", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1053, "Alto Baudo (Pie de Pato)", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1054, "Atrato (Yuto)", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1055, "Bagado", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1056, "Bahia Solano (Mutis)", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1057, "Bajo Baudo (Pizarro)", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1058, "Bojaya (Bellavista)", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1059, "Canton de San Pablo", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1060, "Condoto", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1061, "El Carmen", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1062, "El Litoral de San Juan", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1063, "Itsmina", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1064, "Jurado", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1065, "Lloro", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1066, "Novita", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1067, "Nuqui", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1068, "Quibdo", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1069, "Riosucio", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1070, "San Jose del Palmar", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1071, "Sipi", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1072, "Tado", 33 );
INSERT INTO cities(`id`, `name`, `department_id`) VALUES (1073, "Unguia", 33 );
